spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: postgres
    password: 050725500261
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

    logging:
      level:
        root: info
        com.example.internship: debug  # Укажи свой package!
      pattern:
        console: "%d{HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

